os: linux
arch: ppc64le
dist: focal

before_script:
  - chmod +x script.sh

services:
  - docker
  
script:
  - docker run -t --rm -v $PWD:/tmp registry.access.redhat.com/ubi8/ubi:8.5 bash -c "/tmp/script.sh"
