os: linux
arch: ppc64le
dist: focal
language: shell

before_script:
  - chmod +x script.sh

services:
  - docker
  
script:
  - docker run -t --rm -v $PWD:/home/tester registry.access.redhat.com/ubi8/ubi:8.5 bash -c "/home/tester/script.sh"
